### ISSUE TITLE
type/value mismatch: boost::shared_ptr<boost::asio::strand>

### ISSUE THREAD

**Issue by narutojxl** [wvu-navLab/CN-GP#3]
Hello author,
When i `catkin_make` to build, it terminated with this. My OS is ubuntu20.04, `libboost1.71-dev`. How to deal with, thanks in advance!
>
	[ 62%] Building CXX object corenav-GP/hw_interface/CMakeFiles/base_interface.dir/src/base_interface.cpp.o
	In file included from /home/jxl/jxl/corenav-GP_ws/src/corenav-GP/hw_interface/src/base_interface.cpp:3:
	/home/jxl/jxl/corenav-GP_ws/src/corenav-GP/hw_interface/include/hw_interface/base_interface.hpp:105:46: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class boost::shared_ptr’
	  105 |         boost::shared_ptr<boost::asio::strand> interfaceSynchronousStrand;
	      |                                              ^
	/home/jxl/jxl/corenav-GP_ws/src/corenav-GP/hw_interface/include/hw_interface/base_interface.hpp:105:46: note:   expected a type, got ‘strand’
	/home/jxl/jxl/corenav-GP_ws/src/corenav-GP/hw_interface/include/hw_interface/base_interface.hpp: In member function ‘virtual bool base_classes::base_interface::interfaceReady()’:

**Comment by cagrikilic** [comment]
Hello,
The package is tested for ROS Melodic in ubuntu18.04, and it looks like a boost library problem. Currently there is no support for ROS Noetic in ubuntu20.04. 

However, the hw_interface,  hw_interface_plugins, gps_core_navigation, pathfinder_control, init_core_navigation, and novatel_launch folders are only needed for the specific setup as described in the corresponding paper for this software. So, you can add CATKIN_IGNORE inside of these packages, and commenting out the hw_interface_plugin_roboteq (line 8 at ~/corenav-GP/src/core_navigation) to compile the main software in ubuntu20.04. 

Please re-open this issue, if it doesn't work.
Thanks.

**Comment by narutojxl** [comment]
Hello author @cagrikilic , i add `CATKIN_IGNORE` into the aboving packages.  I find there is no `GP_Input.h` ,  `GP_Output.h` and `SetStopping.h`. If I comment these include files and `core_nav::GP_Input slip_msg;`, `core_nav::GP_Output gp_data_;` and `bool setStopping_(core_nav::SetStopping::Request &req, core_nav::SetStopping::Response &res);` in `CoreNav.h`, these are also many comment places in `CoreNav.cpp`. How can i find  three include files, thanks for  your help.
https://github.com/wvu-navLab/corenav-GP/blob/db4c04fb1d0c9a7222cec29800dd3a838ab9903e/core_navigation/include/core_navigation/CoreNav.h#L20-L21
https://github.com/wvu-navLab/corenav-GP/blob/db4c04fb1d0c9a7222cec29800dd3a838ab9903e/core_navigation/include/core_navigation/CoreNav.h#L26

**Comment by narutojxl** [comment]
Hello author, it works, thanks again. Supplement the following information for noetic users.
* corenav-GP need `novatel_gps_msgs`, can build from [novatel_gps_driver](https://github.com/swri-robotics/novatel_gps_driver).
* `core_nav` package needs to buid `core_nav/msg/GP_Input.msg` , `core_nav/msg/GP_Output.msg` and `core_nav/srv/SetStopping.srv` firstly to create include files, so comment `core_nav/CMakeLists.txt`  create targets lines, such as `add_library(), add_executable() and target_link_libraries()` firstly. After built msg, then to build `core_nav`.
* `gp_predictor` needs `core_nav`, add CATKIN_IGNORE firstly  into this. After built `core_nav`, remove CATKIN_IGNORE and then to build `gp_predictor`.
